name: CI on PR to main

on:
  pull_request:
    branches: 
      - main

jobs:
  integrate_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: CD to src/frontend
        run: cd ./src/frontend
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
